### ISSUE TITLE
Javascript one-line comments (//) stop the rest of the script execution in Yamcs Studio 1.0.5

### ISSUE THREAD

**Issue by tomvanbraeckel** [yamcs/yamcs-studio#85] opened 2019-06-07 11:55 UTC
We have a few displays with buttons that execute a .js file when you click it, but this no longer works in Yamcs Studio v1.0.5. Embedded Javascript works, though.

It works in Yamcs Studio v1.0.2.

The commit that seems to cause this regression is 1fa3337c44b326a0 because reverting it fixes the issue. But that commit fixes a memory leak so I don't want to revert it.

**Comment by fqqb** [comment] 2019-06-17 08:18
I tried but could not reproduce this one as described.
Can you send me a failing display file?

**Comment by tomvanbraeckel** [comment] 2019-06-17 09:35
I've e-mailed the failing display file and the Javascript file that it references.

**Comment by tomvanbraeckel** [comment] 2019-06-18 09:00
Changed the title to reflect the fact that it seems the issue is not external Javascript but the // comments used in such external Javascript...

**Comment by tomvanbraeckel** [comment] 2019-06-18 09:04
Workaround is to use /* and */ comments.

**Comment by fqqb** [comment] 2019-06-18 14:24
Thanks again for the good find.

Fixed on master and on v1.0.x branch.
Included in yamcs-studio v1.0.6

**Closed by fqqb** 2019-06-18 14:24 UTC
