### ISSUE TITLE
Edit tags / Annotations

### ISSUE THREAD

**Issue by nmaas87** [yamcs/yamcs-studio#93] opened 2020-10-06 00:54 UTC
This might be some obscure "RTFM" kind of error, but I personally did not find any possibilty to edit or delete created tags/annotations in neither Yamcs Studio nor the Yamcs Server. I can create them easily in the archive view of Yamcs Studio, but not even rename or delete them. Did I miss something :)?

Thanks a lot

**Comment by fqqb** [comment] 2020-10-06 08:53
You should be able to right click on the them for edit/delete.

But it appears there's some issues when trying to edit/delete newly added tags. If you refresh that view beforehand it should work. I fixed Studio on master for this particular issue, but also Yamcs itself will require an update that we shall include in next release.

**Comment by nmaas87** [comment] 2020-10-06 20:39
I tried to right-click Tags in the Archive Overview in Yamcs Server / Web Interface both in Firefox and Edge, but that did not yield any results. Other than left clicking on the Tags did highlight the correct range for the "Download Dump" option - and hovering a tag showcased start and endtime.

Also in Yamcs Studio Version 1.4.0 RC1 and 1.5.0 I can create new tags in the Archive view, however nothing happens if I right click on them, even if I reload the data manually (click Refresh). [But I can see that the 1.4.0 RC1 client seems not to load the TM data anymore from the 5.1.3 server, even if I click on refresh... no data is shown in the diagram, only white space...)

**Comment by fqqb** [comment] 2020-10-13 14:11
Fixed in Yamcs Studio v1.5.1. Use against Yamcs v5.2.0 for the full annotation/tag fix.

The Web Interface of Yamcs intentionally provides only a readonly view of tags, as I'd prefer most people don't use it. Before we add web support, the server implementation needs to become a lot better.

**Comment by nmaas87** [comment] 2020-10-14 09:19
Tested with Yamcs v.5.2.0 Server and Yamcs Studio v.1.5.1 on Windows 10 with clean Workspace - sadly did not work, sorry :(.
Cannot right click an existing tag and edit or remove. Tried double click, does also nothing. Maybe an issue with Windows 10? However, the JavaScript Error is gone 👍🏻

**Comment by fqqb** [comment] 2020-10-14 14:07
I confirm it's indeed not working on Windows. For other reasons than the ones that i fixed before.

I think the issue is in TagBox.java The pop-up trigger should be checked on both mousePressed and mouseReleased to be cross-platform.

I will prepare a fix for whenever we do the next release. If you want to delete stuff in the meantime you could use a non-windows machine, or directly the API https://yamcs.org/docs/yamcs-http-api/tag/delete-tag/

**Comment by fqqb** [comment] 2020-10-29 16:39
Remaining windows-only issue fixed in Yamcs Studio v1.5.2.

**Closed by fqqb** 2020-10-29 16:39 UTC

**Comment by nmaas87** [comment] 2020-10-30 08:39
I tested this and can confirm it works perfectly.
Thank you very much for your effort and resolving this issue in such a short time :)!
