### ISSUE TITLE
Can't set local PV initial value to empty string

### ISSUE THREAD

**Issue by bitblit11** [yamcs/yamcs-studio#26] opened 2015-10-25 12:36 UTC
The following results in an index out of bounds error:

loc://MyPV<VString>("")

I want to either set the initial value to empty string, or detect the local PV hasn't been set so my script can put an empty string in the command parameter.  I can't set it to empty string.  And detecting not set seems a kludge.  I have to remove the initial value all together, and test the local PV for "no value".  That's "no value" string.  That's a problem if the user actually entered "no value".  Can't tell the difference between if the user entered "no value" or if no value was entered.

**Comment by fqqb** [comment] 2015-10-27 07:32
i have to look in detail what's happening, but my first remark would be that possibly it's because you are referring to `loc://MyPV` for reading it. From what i understand of the CS-Studio local parameters, these are three *different* PV's:

* loc://MyPV
* loc://MyPV("")
* loc://MyPV("abc")

In other words, if you want to be sure to read the value of `loc://MyPV("")`, you always have to specify that initial value as well.

**Comment by fqqb** [comment] 2020-09-28 09:40
Closing because loc:// datasource was reimplemented in v1.5.0 out Today, and anyway I've not been able to reproduce an IndexOutOfBoundsError with this PV.

**Closed by fqqb** 2020-09-28 09:40 UTC
